# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: mattgomes28/jammy-cpp:0.0.0
      options: --user 1001

    steps:
    - uses: actions/checkout@v4

    - name: Run clang format
      run: |
        git ls-files "*.cpp" >> format-files
        git ls-files "*.hpp" >> format-files
        git ls-files "*.h" >> format-files
        clang-format -Werror --dry-run --files=format-files

    - name: Configure CMake
      run: cmake . --preset "unix-deb-ninja"

    - name: Build
      run: cmake --build --preset "unix-deb-ninja"

    - name: Test
      run: ctest --preset "unix-deb-ninja"

